#pragma once

#include <DXD/ExternalHeadersWrappers/windows.h>
#include <dwrite.h>

enum class DXDFontWeight {
    THIN = DWRITE_FONT_WEIGHT_THIN,
    EXTRA_LIGHT = DWRITE_FONT_WEIGHT_EXTRA_LIGHT,
    ULTRA_LIGHT = DWRITE_FONT_WEIGHT_ULTRA_LIGHT,
    LIGHT = DWRITE_FONT_WEIGHT_LIGHT,
    SEMI_LIGHT = DWRITE_FONT_WEIGHT_SEMI_LIGHT,
    NORMAL = DWRITE_FONT_WEIGHT_NORMAL,
    REGULAR = DWRITE_FONT_WEIGHT_REGULAR,
    MEDIUM = DWRITE_FONT_WEIGHT_MEDIUM,
    DEMI_BOLD = DWRITE_FONT_WEIGHT_DEMI_BOLD,
    SEMI_BOLD = DWRITE_FONT_WEIGHT_SEMI_BOLD,
    BOLD = DWRITE_FONT_WEIGHT_BOLD,
    EXTRA_BOLD = DWRITE_FONT_WEIGHT_EXTRA_BOLD,
    ULTRA_BOLD = DWRITE_FONT_WEIGHT_ULTRA_BOLD,
    BLACK = DWRITE_FONT_WEIGHT_BLACK,
    HEAVY = DWRITE_FONT_WEIGHT_HEAVY,
    EXTRA_BLACK = DWRITE_FONT_WEIGHT_EXTRA_BLACK,
    ULTRA_BLACK = DWRITE_FONT_WEIGHT_ULTRA_BLACK
};

enum class DXDFontStyle {
    NORMAL = DWRITE_FONT_STYLE_NORMAL,
    OBLIQUE = DWRITE_FONT_STYLE_OBLIQUE,
    ITALIC = DWRITE_FONT_STYLE_ITALIC
};

enum class DXDFontStretch {
    UNDEFINED = DWRITE_FONT_STRETCH_UNDEFINED,
    ULTRA_CONDENSED = DWRITE_FONT_STRETCH_ULTRA_CONDENSED,
    EXTRA_CONDENSED = DWRITE_FONT_STRETCH_EXTRA_CONDENSED,
    CONDENSED = DWRITE_FONT_STRETCH_CONDENSED,
    SEMI_CONDENSED = DWRITE_FONT_STRETCH_SEMI_CONDENSED,
    NORMAL = DWRITE_FONT_STRETCH_NORMAL,
    MEDIUM = DWRITE_FONT_STRETCH_MEDIUM,
    SEMI_EXPANDED = DWRITE_FONT_STRETCH_SEMI_EXPANDED,
    EXPANDED = DWRITE_FONT_STRETCH_EXPANDED,
    EXTRA_EXPANDED = DWRITE_FONT_STRETCH_EXTRA_EXPANDED,
    ULTRA_EXPANDED = DWRITE_FONT_STRETCH_ULTRA_EXPANDED
};

enum class DXDTextHorizontalAlignment {
    LEFT = DWRITE_TEXT_ALIGNMENT_LEADING,
    RIGHT = DWRITE_TEXT_ALIGNMENT_TRAILING,
    CENTER = DWRITE_TEXT_ALIGNMENT_CENTER,
    JUSTIFIED = DWRITE_TEXT_ALIGNMENT_JUSTIFIED
};

enum class DXDTextVerticalAlignment {
    TOP = DWRITE_PARAGRAPH_ALIGNMENT_NEAR,
    BOTTOM = DWRITE_PARAGRAPH_ALIGNMENT_FAR,
    CENTER = DWRITE_PARAGRAPH_ALIGNMENT_CENTER
};